### ISSUE TITLE
Menu visibility problem

### ISSUE THREAD

**Issue by malyjak** [sharvaridesai/hexo-theme-edinburgh#23]
After adding

```
# Header
menu:
  About: /about
  Contact: /contact
  Instagram: https://www.instagram.com
  LinkedIn: https://www.linkedin.com
  Facebook: https://www.facebook.com
```
to 'themes/edinburgh/_config.yml' and doing

```
hexo new page about
hexo new page contact
```

menu is still not visible.
